// 1. Chỉnh sửa các dòng chữ theo mục đích của bạn
const CONFIG = {
    introTitle: 'Chào Cục Cưng của Anh nà😊!!',
    introDesc: `Hơi dài dòng 1 xíu, Bé đọc kỹ nha hơmmm <3`,
    btnIntro: 'Đi Thoiiii',
    title: 'New Year And NEW LOVE 😙',
    desc: 'Chào Cục Cưng của Anh nhá💖. Khi Em thấy được tin nhắn này là Bé sắp chính thức có người yêu rồi ớ🤭.Hôm nay là ngày 1/2/2022 Cũng là ngày mùng 1 tết nguyên đán ó🎆. Anh cũm hong biết sao nhưng anh đợi ngày này cũng hơi lâu đó. Ngày mà mình có thể chính thức gọi Em là người yêu🤭. Bữa giờ cũng gọi như thế cũng vui nhưng mà hơi ngượng ngượng kiểu gì ớ😅. Anh chọn hôm nay thì anh đợi hết nỗi oiiii, và cũng là ngày đẹp nhất trong thời gian gần đây. Ngày mai 2/2/2022 có thể đẹp hơn về hình thức nhưng mà hong liên quan gì mình hết ớ. Nay 1/2 có 1 có 2 trong 0201 của em và 12 trong ngày sinh của Anh😊, cùng là ngày đầu tháng 2, và là đầu năm Nhâm Dần. Coi như đây là sự khởi đầu tốt đẹp và may mắn của 2 đứa mình nha💖.Trước tiên, Chúc Bé iu năm mới tuổi mới vui vẻ, hạnh phúc bên gia đình và Anh. Có thật nhiều sức khoẻ nè, ngày càng xinh đẹp dễ thưn ạ. Gửi lời hỏi thăm sức khoẻ đến bame ông bà và Em trai Em luôn, chúc gia đình thật nhiều sức khoẻ và vạn sự như ý á <3. Tiếp theo, Tính ra cũng tròn 28 ngày mình quen nhau gòi ha, 4 tuần chẵn luôn, mặc dù hơi ngắn thiệt nhưng những gì trải qua cũng chỉ có 2 đứa hiểu. Tình cảm đi đến đâu cũng 2 đứa biết và vì gì mà như vậy thì chúng ta cũng hiểu rõ nhất oiiii💖.Quen biết Em thật ra Anh rất may mắn lắm ớ, có người yêu vừa dễ thương nè😍, học giỏi nè🤩, ngoan ngoãn nè🥳. Gòi tính cách cũng (hơi) giống nhau nên Anh cũng biết sơ sơ là những điều gì làm Em khó chịu và những gì làm em vui😜. Nói ngắn gọn là 2 đứa giống như làm 1 dị á. Nếu lỡ Em lần này chắc chắn rất rất khó tìm được người thứ 2 như v luôn🤭. 21 năm qua mới thấy một người làm Anh vui như z, gòi giống mình như z nữa. Vậy Anh hong muốn bỏ lỡ cơ hội có 102 này...Anh biết bé hong thích đọc dài😛,  nên có gì chúng mình gặp nhau gòi từ từ nói cũng hết àaaaa. Như z mới có nhìu cơ hội gặp nhau chớ đúng hong.🤭Vì vậy, Cho Anh 1 cơ hội được BÊN EM, QUAN TÂM, CHĂM SÓC VÀ LO LẮNG CHO EM NHÁ 💖, Anh hứa SẼ CỐ GẮNG HẾT SỨC HONG LÀM EM BUỒN, HONG LÀM EM LO LẮNG HAY THẤT VỌNG VỀ ANH ĐÂU. Anh cũng không bao giờ buông tay hay bỏ rơi cục cưng của Anh dù chuyện gì đi nữa. Dù có chuyện gì cũng mạnh mẽ lên, cùng Anh bước qua, lúc nào sau lưng bé cũng có Anh và gia đình nè 💖. Khi em vào đây là em phải TRẢ LỜI LÀ YesICan mới mở cửa cho ra nhaaaaa. Đó cũng là câu trả lời Anh muốn nghe từ Em ngày hôm nay. Cuối Cùng Anh muốn nói là : Can you agree to be my lover? 💖Trả lời qua tin nhắn mess nhá. chỉ cần ghi câu trả lời hoiiiii. Anh Yêu Em nhiều lắm lắm. Cùng nhau trải qua thật nhiều 14/2 ròi tới happy ending nhaaaaaa cục cưng...moaaa ',
    btnYes: 'Yes I Can 💖💖',
    btnNo: 'Em chỉ có 1 sự lựa chọn là Yes hoiii. liuliu😛😛 ',
    question:'Cảm ơn Công chúa nhỏ đồng ý nhá <3 <3 <3, zuiiii quá troi hong biết nói gì luôn. Bé có gì muốn nói với Anh hong, nhập vô đây ngắn gọn hoiiii 😊😊',
    reasonPlaceholder: 'Mời Bé Iu nhập nàaaaaa',
    btnReply: 'Gởi ! 💌💌',
    reply: 'Em cũng Yêu Anh lắm lắm lắm á😊😊😜😜🤣🤣',
    mess: 'Anh biết mà, Người Yêu Anh phải thế chớ, Anh Yêu Bé Yêu Bé Yêu Bé nhiều nhiều 🥰😘😘',
    messDesc: 'Hong biết nói gì hơn, Anh chỉ muốn nói thêm là Em chỉ cần TIN TƯỞNG ANH, YÊU ANH, BÊN CẠNH ANH, mọi chuyện còn lại để Anh lo. Thương bé nhiều nhất á <3. HAPPY NEW YEAR Người Anh Thương, Chúc mừng Anh đã có EM oiiiiiii',
    btnAccept: 'Đón Tết cùng NY hoiiii <3💖',
    messLink: 'https://m.me/Duykhiem2205'
}
